apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfacto.fullname" . }}-postgres
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  db: {{ .Values.postgres.database | b64enc }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfacto.fullname" . }}-postgres
  labels:
    app: {{ include "postfacto.fullname" . }}-postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: {{ include "postfacto.fullname" . }}-postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postfacto.fullname" . }}-postgres
  labels:
    app: {{ include "postfacto.fullname" . }}-postgres
spec:
  serviceName: {{ include "postfacto.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postfacto.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "postfacto.fullname" . }}-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "postfacto.fullname" . }}-postgres
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postfacto.fullname" . }}-postgres
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "postfacto.fullname" . }}-postgres
              key: db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "postfacto.fullname" . }}-postgres-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "postfacto.fullname" . }}-postgres-claim
  labels:
    app: postfacto-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
